from xtuner.utils.constants import DEFAULT_IMAGE_TOKEN, IMAGE_TOKEN_INDEX

DEFAULT_SEG_TOKEN = "<SEG>"
DEFAULT_CLS_TOKEN = "<CLS>"
DEFAULT_PSTART_TOKEN = "<p>"
DEFAULT_PEND_TOKEN = "</p>"
DEFAULT_REGION_TOKEN = "<region>"
REGION_TOKEN_INDEX = -300

DEFAULT_TASKS = ["imgconv", "genseg", "refseg", "reaseg", "gcgseg", "ovseg", "intseg", "vgdseg"]
TOKEN2INDEX = {
    DEFAULT_IMAGE_TOKEN: IMAGE_TOKEN_INDEX,
    DEFAULT_REGION_TOKEN: REGION_TOKEN_INDEX,
}
DEFAULT_SPECIAL_TOKENS = [DEFAULT_PEND_TOKEN, DEFAULT_PSTART_TOKEN, DEFAULT_SEG_TOKEN, DEFAULT_CLS_TOKEN]
INDEX2TOKEN = {v: k for k, v in TOKEN2INDEX.items()}
